[".zsh/plugins/zsh-helix-mode"]
type = "git-repo"
url = "https://github.com/Multirious/zsh-helix-mode.git"
refreshPeriod = "168h"

[ ".zsh/plugins/zsh-helix-mode".clone ]
args = ["--depth=1"]

[".zsh/plugins/zsh-autosuggestions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-autosuggestions.git"
refreshPeriod = "168h"

[".zsh/plugins/zsh-autosuggestions".clone]
args = ["--depth=1"]

[".zsh/plugins/zsh-syntax-highlighting"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
refreshPeriod = "168h"

[".zsh/plugins/zsh-syntax-highlighting".clone]
args = ["--depth=1"]

["helix.vim"]
type = "git-repo"
url = "https://github.com/chtenb/helix.vim.git"
refreshPeriod = "168h"

[ "helix.vim".clone ]
args = ["--depth=1"]

[".vim/pack/themes/opt/tokyonight-vim"]
type = "git-repo"
url = "https://github.com/ghifarit53/tokyonight-vim.git"
refreshPeriod = "168h"

[ ".vim/pack/themes/opt/tokyonight-vim".clone ]
args = ["--depth=1"]
