[mgr]
ratio = [1, 1, 2]

[opener]
pdf = [
	{ run = 'zathura %s1', desc = "Zathura", orphan = true },
]
micro = [
	{ run = 'micro %s', desc = "Micro", block = true, for = "unix" },
]

[[open.prepend_rules]]
mime = "application/pdf"
use = "pdf"

[[open.prepend_rules]]
url = "*.txt"
use = "micro"
